### ISSUE TITLE
Missing return in mappings?

### ISSUE THREAD

**Issue by lervag** [rbong/vim-flog#85]
I noticed that some of the rebase mappings do not have the final `<cr>` in the definitions:

https://github.com/rbong/vim-flog/blob/fb137707b84a328d3f1b53d22894e3c52f4a6ddb/ftplugin/floggraph.vim#L342-L352

Is this on purpose? If not, I could push a PR (unless you want to fix it yourself).

**Comment by rbong** [comment]
Good catch, no it is not on purpose. PRs are always appreciated.

**Comment by lervag** [comment]
PR #86 has been pushed and should fix this.

**Comment by rbong** [comment]
This is still an issue in v2, just reopening this so I don't lose track for now

**Comment by lervag** [comment]
Ah, I see. No problem :)

**Comment by rbong** [comment]
Fixed in v2

**Comment by lervag** [comment]
Thanks!
